{
	"version": 1701191260,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tilemap.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/sprite2-sheet0.png",
		"images/pngtransparentpixelheartthumbnailremovebgpreview-sheet0.png",
		"images/bar2-sheet0.png",
		"images/bar-sheet0.png",
		"images/hert-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/spawner-sheet0.png",
		"images/f3e73d3ca00b4b59f4efd67809eb-sheet0.png",
		"images/cfbcd4336297cddremovebgpreview-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/plo-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/b-sheet0.png",
		"images/b2-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite7-sheet1.png",
		"images/sprite7-sheet2.png",
		"images/arm_projectile-sheet0.png",
		"images/the_answer_is_____4_removebgpreview-sheet0.png",
		"images/particles.png",
		"images/particles2.png",
		"images/right_-sheet0.png",
		"images/jmp-sheet0.png",
		"images/punch-sheet0.png",
		"images/boom-sheet0.png",
		"images/untitled__2_removebgpreview-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/the_answer_is_____1_removebgpreview-sheet0.png",
		"images/theansweris-sheet0.png",
		"media/boom.ogg",
		"media/foot.ogg",
		"media/jump.ogg",
		"media/theme.ogg",
		"media/damage.ogg",
		"media/lasershoot.m4a",
		"media/lasershoot.ogg",
		"media/lasershoot (1).m4a",
		"media/lasershoot (1).ogg",
		"media/new_project (1).m4a",
		"media/new_project (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}